import type { Product, Store, Category, Deal } from "./types"

export const categories: Category[] = [
  {
    id: "electronics",
    name: "Electronics",
    slug: "electronics",
    description: "Phones, computers, gaming, and electronic accessories",
    icon: "Smartphone",
    productCount: 15420,
    featured: true,
    subcategories: [
      {
        id: "phones",
        name: "Mobile Phones",
        slug: "phones",
        description: "",
        icon: "Smartphone",
        productCount: 3200,
        featured: false,
      },
      {
        id: "computers",
        name: "Computers & Laptops",
        slug: "computers",
        description: "",
        icon: "Laptop",
        productCount: 2100,
        featured: false,
      },
      {
        id: "gaming",
        name: "Gaming",
        slug: "gaming",
        description: "",
        icon: "Gamepad2",
        productCount: 1800,
        featured: false,
      },
      {
        id: "audio",
        name: "Audio & Headphones",
        slug: "audio",
        description: "",
        icon: "Headphones",
        productCount: 1500,
        featured: false,
      },
    ],
  },
  {
    id: "fashion",
    name: "Fashion & Clothing",
    slug: "fashion",
    description: "Clothing, shoes, accessories for men, women, and children",
    icon: "Shirt",
    productCount: 28500,
    featured: true,
    subcategories: [
      {
        id: "mens-clothing",
        name: "Men's Clothing",
        slug: "mens-clothing",
        description: "",
        icon: "User",
        productCount: 8500,
        featured: false,
      },
      {
        id: "womens-clothing",
        name: "Women's Clothing",
        slug: "womens-clothing",
        description: "",
        icon: "User",
        productCount: 12000,
        featured: false,
      },
      {
        id: "shoes",
        name: "Shoes & Footwear",
        slug: "shoes",
        description: "",
        icon: "Footprints",
        productCount: 5200,
        featured: false,
      },
      {
        id: "accessories",
        name: "Accessories",
        slug: "accessories",
        description: "",
        icon: "Watch",
        productCount: 2800,
        featured: false,
      },
    ],
  },
  {
    id: "home-furniture",
    name: "Home & Furniture",
    slug: "home-furniture",
    description: "Furniture, home decor, kitchen, and household items",
    icon: "Home",
    productCount: 18700,
    featured: true,
    subcategories: [
      {
        id: "furniture",
        name: "Furniture",
        slug: "furniture",
        description: "",
        icon: "Armchair",
        productCount: 6500,
        featured: false,
      },
      {
        id: "kitchen",
        name: "Kitchen & Dining",
        slug: "kitchen",
        description: "",
        icon: "ChefHat",
        productCount: 4200,
        featured: false,
      },
      {
        id: "decor",
        name: "Home Decor",
        slug: "decor",
        description: "",
        icon: "Palette",
        productCount: 3800,
        featured: false,
      },
      {
        id: "garden",
        name: "Garden & Outdoor",
        slug: "garden",
        description: "",
        icon: "Trees",
        productCount: 4200,
        featured: false,
      },
    ],
  },
  {
    id: "vehicles",
    name: "Vehicles & Parts",
    slug: "vehicles",
    description: "Cars, motorcycles, bicycles, and automotive parts",
    icon: "Car",
    productCount: 8900,
    featured: true,
    subcategories: [
      { id: "cars", name: "Cars", slug: "cars", description: "", icon: "Car", productCount: 2100, featured: false },
      {
        id: "motorcycles",
        name: "Motorcycles",
        slug: "motorcycles",
        description: "",
        icon: "Bike",
        productCount: 1800,
        featured: false,
      },
      {
        id: "auto-parts",
        name: "Auto Parts",
        slug: "auto-parts",
        description: "",
        icon: "Settings",
        productCount: 3200,
        featured: false,
      },
      {
        id: "bicycles",
        name: "Bicycles",
        slug: "bicycles",
        description: "",
        icon: "Bike",
        productCount: 1800,
        featured: false,
      },
    ],
  },
  {
    id: "agriculture",
    name: "Agriculture & Tools",
    slug: "agriculture",
    description: "Farm equipment, tools, seeds, and agricultural supplies",
    icon: "Tractor",
    productCount: 5600,
    featured: true,
    subcategories: [
      {
        id: "farm-tools",
        name: "Farm Tools",
        slug: "farm-tools",
        description: "",
        icon: "Wrench",
        productCount: 2100,
        featured: false,
      },
      {
        id: "seeds",
        name: "Seeds & Plants",
        slug: "seeds",
        description: "",
        icon: "Sprout",
        productCount: 1500,
        featured: false,
      },
      {
        id: "livestock",
        name: "Livestock & Poultry",
        slug: "livestock",
        description: "",
        icon: "Beef",
        productCount: 800,
        featured: false,
      },
      {
        id: "irrigation",
        name: "Irrigation",
        slug: "irrigation",
        description: "",
        icon: "Droplets",
        productCount: 1200,
        featured: false,
      },
    ],
  },
  {
    id: "health-beauty",
    name: "Health & Beauty",
    slug: "health-beauty",
    description: "Healthcare products, cosmetics, and personal care",
    icon: "Heart",
    productCount: 12300,
    featured: false,
  },
  {
    id: "sports",
    name: "Sports & Recreation",
    slug: "sports",
    description: "Sports equipment, fitness gear, and outdoor activities",
    icon: "Dumbbell",
    productCount: 7800,
    featured: false,
  },
  {
    id: "books-education",
    name: "Books & Education",
    slug: "books-education",
    description: "Books, educational materials, and learning resources",
    icon: "Book",
    productCount: 4500,
    featured: false,
  },
]

export const sampleProducts: Product[] = [
  {
    id: "1",
    name: "Samsung Galaxy A54 5G Smartphone",
    description: "Latest Samsung smartphone with 5G connectivity, 50MP camera, and long-lasting battery",
    price: 450000,
    originalPrice: 520000,
    discount: 13,
    images: ["/placeholder.svg?height=300&width=300"],
    category: "Electronics",
    subcategory: "Mobile Phones",
    categories: ["electronics", "phones"],
    condition: "new",
    rating: 4.6,
    reviewCount: 1250,
    sellerId: "1",
    sellerName: "TechHub Malawi",
    sellerType: "business",
    storeId: "techhub-store",
    storeName: "TechHub Malawi",
    location: "Lilongwe",
    inStock: true,
    stockCount: 25,
    tags: ["smartphone", "5g", "samsung"],
    variants: [
      { id: "color-blue", name: "Color", value: "Awesome Blue", stockCount: 10 },
      { id: "color-black", name: "Color", value: "Awesome Black", stockCount: 15 },
      { id: "storage-128", name: "Storage", value: "128GB", stockCount: 20 },
      { id: "storage-256", name: "Storage", value: "256GB", priceAdjustment: 80000, stockCount: 5 },
    ],
    specifications: {
      Display: "6.4-inch Super AMOLED",
      Processor: "Exynos 1380",
      RAM: "8GB",
      Storage: "128GB/256GB",
      Camera: "50MP + 12MP + 5MP",
      Battery: "5000mAh",
      OS: "Android 13",
    },
    bulkPricing: [
      { minQuantity: 5, price: 430000, discount: 4 },
      { minQuantity: 10, price: 410000, discount: 9 },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    name: "John Deere Tractor Model 5075E",
    description: "Reliable farm tractor perfect for small to medium farming operations",
    price: 15500000,
    originalPrice: 17000000,
    discount: 9,
    images: ["/placeholder.svg?height=300&width=300"],
    category: "Agriculture",
    subcategory: "Farm Equipment",
    categories: ["agriculture", "farm-tools", "vehicles"],
    condition: "new",
    rating: 4.8,
    reviewCount: 89,
    sellerId: "2",
    sellerName: "AgriEquip Malawi",
    sellerType: "business",
    storeId: "agriequip-store",
    storeName: "AgriEquip Malawi",
    location: "Blantyre",
    inStock: true,
    stockCount: 3,
    tags: ["tractor", "farming", "john-deere"],
    specifications: {
      Engine: "4-cylinder diesel",
      Power: "75 HP",
      Transmission: "8F/8R PowrReverser",
      Hydraulics: "Open center",
      PTO: "540/1000 rpm",
      Weight: "3,200 kg",
    },
    minOrderQuantity: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    name: "Traditional Malawian Chitenje Fabric",
    description: "Authentic handwoven chitenje fabric in vibrant colors, perfect for traditional wear",
    price: 8500,
    images: ["/placeholder.svg?height=300&width=300"],
    category: "Fashion",
    subcategory: "Traditional Wear",
    categories: ["fashion", "traditional"],
    condition: "new",
    rating: 4.9,
    reviewCount: 340,
    sellerId: "3",
    sellerName: "Malawi Textiles Co.",
    sellerType: "business",
    storeId: "malawi-textiles",
    storeName: "Malawi Textiles Co.",
    location: "Mzuzu",
    inStock: true,
    stockCount: 150,
    tags: ["chitenje", "traditional", "fabric"],
    variants: [
      { id: "pattern-1", name: "Pattern", value: "Geometric Blue", stockCount: 50 },
      { id: "pattern-2", name: "Pattern", value: "Floral Red", stockCount: 60 },
      { id: "pattern-3", name: "Pattern", value: "Abstract Green", stockCount: 40 },
    ],
    bulkPricing: [
      { minQuantity: 10, price: 7500, discount: 12 },
      { minQuantity: 50, price: 6800, discount: 20 },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    name: "Mahogany Dining Table Set",
    description: "Handcrafted solid mahogany dining table with 6 chairs, showcasing Malawian craftsmanship",
    price: 285000,
    originalPrice: 320000,
    discount: 11,
    images: ["/placeholder.svg?height=300&width=300"],
    category: "Home & Furniture",
    subcategory: "Furniture",
    categories: ["home-furniture", "furniture"],
    condition: "new",
    rating: 4.7,
    reviewCount: 67,
    sellerId: "4",
    sellerName: "Malawi Woodworks",
    sellerType: "business",
    storeId: "malawi-woodworks",
    storeName: "Malawi Woodworks",
    location: "Lilongwe",
    inStock: true,
    stockCount: 8,
    tags: ["mahogany", "dining-table", "handcrafted"],
    specifications: {
      Material: "Solid Mahogany Wood",
      "Table Size": "180cm x 90cm x 75cm",
      "Chair Dimensions": "45cm x 45cm x 90cm",
      Finish: "Natural wood stain",
      Seating: "6 people",
      Weight: "85 kg",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const sampleStores: Store[] = [
  {
    id: "techhub-store",
    name: "TechHub Malawi",
    description: "Leading electronics retailer in Malawi, offering latest smartphones, computers, and tech accessories",
    logo: "/placeholder.svg?height=100&width=100",
    banner: "/placeholder.svg?height=200&width=800",
    ownerId: "1",
    ownerName: "TechHub Ltd",
    rating: 4.7,
    reviewCount: 2340,
    productCount: 156,
    location: "Lilongwe",
    isVerified: true,
    categories: ["Electronics", "Gaming", "Computers"],
    businessType: "enterprise",
    establishedYear: 2018,
    responseTime: "Within 2 hours",
    createdAt: new Date(),
  },
  {
    id: "agriequip-store",
    name: "AgriEquip Malawi",
    description: "Specialized in agricultural equipment and farming tools for modern Malawian farmers",
    logo: "/placeholder.svg?height=100&width=100",
    banner: "/placeholder.svg?height=200&width=800",
    ownerId: "2",
    ownerName: "AgriEquip Solutions",
    rating: 4.8,
    reviewCount: 890,
    productCount: 89,
    location: "Blantyre",
    isVerified: true,
    categories: ["Agriculture", "Tools", "Vehicles"],
    businessType: "small_business",
    establishedYear: 2015,
    responseTime: "Within 4 hours",
    createdAt: new Date(),
  },
]

export const flashDeals: Deal[] = [
  {
    id: "deal-1",
    title: "Electronics Flash Sale",
    description: "Up to 30% off on selected electronics",
    productIds: ["1"],
    discountPercentage: 30,
    startDate: new Date(),
    endDate: new Date(Date.now() + 24 * 60 * 60 * 1000), // 24 hours from now
    maxQuantity: 50,
    usedQuantity: 23,
  },
  {
    id: "deal-2",
    title: "Fashion Week Special",
    description: "Traditional wear at amazing prices",
    productIds: ["3"],
    discountPercentage: 25,
    startDate: new Date(),
    endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 7 days from now
    maxQuantity: 100,
    usedQuantity: 45,
  },
]
